export const cityOptions = [
  { key: 'csm', value: 'csm', text: '77 - Champs-sur-Marne' },
  { key: 'cb', value: 'cb', text: '77 - Croissy Beaubourg' },
  { key: 'em', value: 'em', text: '77 - Émerainville' },
  { key: 'lo', value: 'lo', text: '77 - Lognes' },
  { key: 'nl', value: 'nl', text: '77 - Noisiel' },
  { key: 'ty', value: 'ty', text: '77 - Torcy' },
  { key: 'bsg', value: 'bsg', text: '77 - Bussy-Saint-Georges' },
  { key: 'bsm', value: 'bsm', text: '77 - Bussy-Saint-Martin' },
  { key: 'ceb', value: 'ceb', text: '77 - Chanteloup-en-Brie' },
  { key: 'col', value: 'col', text: '77 - Collégien' },
  { key: 'csg', value: 'csg', text: '77 - Conches-sur-Gondoire' },
  { key: 'to', value: 'to', text: '77 - Thorigny-sur-Marne' },
  { key: 'mo', value: 'mo', text: '77 - Montévrain' },
  { key: 'stv', value: 'stv', text: '77 - Saint-Thibault-des-Vignes' },
  { key: 'br', value: 'br', text: '77 - Bailly-Romainvilliers' },
  { key: 'ch', value: 'ch', text: '77 - Chessy' },
  { key: 'co', value: 'co', text: '77 - Coupvray' },
  { key: 'mh', value: 'mh', text: '77 - Magny-le-Hongre' },
  { key: 'se', value: 'se', text: '77 - Serris' },
  { key: 'vc', value: 'vc', text: '77 - Villeneuve le Comte' },
  { key: 'ng', value: 'ng', text: '93 - Noisy-le-Grand' },
  { key: 'bm', value: 'bm', text: '94 - Bry-sur-Marne' },
  { key: 'vm', value: 'vm', text: '94 - Villiers-sur-Marne' },
  { key: 'au', value: 'au', text: 'Autre' }
];
